FROM alpine:3.8
RUN apk --no-cache add iproute2 iptables ipset
WORKDIR /root/
COPY ./static-egressip-controller /usr/local/bin/static-egressip-controller

ENTRYPOINT ["/usr/local/bin/static-egressip-controller"]